# Generated by Django 4.2 on 2023-04-07 18:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_agent_is_admin_remove_agent_is_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
        migrations.AddField(
            model_name='addresscheckerusage',
            name='address_requested',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='addresscheckerusage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='addresscheckerusage',
            name='sale_associated',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.salesdata'),
        ),
        migrations.AddField(
            model_name='addresscheckerusage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directories',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='directories',
            name='postalcode',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='directories',
            name='radius_mile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directories',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='appointmentdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='appointmenttime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='clientaddress',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='clientemail',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='clientname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='clientphone',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamleader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('bank_details', main.fields.BankDetailsField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
